# Form implementation generated from reading ui file 'C:\Users\Stanislawski\Desktop\МРПС\Programm\interfaces\admin_main.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminWindowMain(object):
    def setupUi(self, AdminWindowMain):
        AdminWindowMain.setObjectName("AdminWindowMain")
        AdminWindowMain.resize(1442, 832)
        self.centralwidget = QtWidgets.QWidget(parent=AdminWindowMain)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(0, 0, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_del = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_del.setGeometry(QtCore.QRect(349, 0, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_cost = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_cost.setGeometry(QtCore.QRect(1070, 0, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_cost.setFont(font)
        self.pushButton_cost.setObjectName("pushButton_cost")
        self.pushButton_date = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_date.setGeometry(QtCore.QRect(700, 0, 372, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_date.setFont(font)
        self.pushButton_date.setObjectName("pushButton_date")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(0, 750, 1441, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 50, 1441, 701))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget::item { border-bottom: 1px solid black; }\n"
"QListWidget::item:selected { background-color: lightblue; color: black; }")
        self.listWidget.setObjectName("listWidget")
        AdminWindowMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AdminWindowMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1442, 21))
        self.menubar.setObjectName("menubar")
        AdminWindowMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AdminWindowMain)
        self.statusbar.setObjectName("statusbar")
        AdminWindowMain.setStatusBar(self.statusbar)

        self.retranslateUi(AdminWindowMain)
        QtCore.QMetaObject.connectSlotsByName(AdminWindowMain)

    def retranslateUi(self, AdminWindowMain):
        _translate = QtCore.QCoreApplication.translate
        AdminWindowMain.setWindowTitle(_translate("AdminWindowMain", "Админ главная"))
        self.pushButton_add.setText(_translate("AdminWindowMain", "Добавить рейс"))
        self.pushButton_del.setText(_translate("AdminWindowMain", "Удалить рейс"))
        self.pushButton_cost.setText(_translate("AdminWindowMain", "Изменить цену на рейс"))
        self.pushButton_date.setText(_translate("AdminWindowMain", "Изменить дату рейса"))
        self.pushButton_exit.setText(_translate("AdminWindowMain", "Выйти из под-системы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminWindowMain = QtWidgets.QMainWindow()
    ui = Ui_AdminWindowMain()
    ui.setupUi(AdminWindowMain)
    AdminWindowMain.show()
    sys.exit(app.exec())
