# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buy_tic.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIntValidator
from PyQt6.QtCore import QRegularExpression


class Ui_buy_tic(object):
    def setupUi(self, buy_tic):
        buy_tic.setObjectName("buy_tic")
        buy_tic.resize(700, 470)
        self.centralwidget = QtWidgets.QWidget(buy_tic)
        self.centralwidget.setObjectName("centralwidget")
        self.box_gender = QtWidgets.QComboBox(self.centralwidget)
        self.box_gender.setGeometry(QtCore.QRect(240, 170, 70, 40))
        self.box_gender.setCurrentText("ПОЛ")
        self.box_gender.setMaxVisibleItems(10)
        self.box_gender.setObjectName("box_gender")
        self.box_gender.addItem("")
        self.box_gender.addItem("")
        self.but_buy = QtWidgets.QPushButton(self.centralwidget)
        self.but_buy.setGeometry(QtCore.QRect(370, 370, 200, 40))
        self.but_buy.setObjectName("but_buy")
        self.but_buy_2 = QtWidgets.QPushButton(self.centralwidget)
        self.but_buy_2.setGeometry(QtCore.QRect(160, 370, 200, 40))
        self.but_buy_2.setObjectName("but_buy_2")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(340, 170, 151, 41))
        self.dateEdit.setObjectName("dateEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setPlaceholderText("Фамилия")
        self.lineEdit.setGeometry(QtCore.QRect(240, 20, 251, 41))
        self.lineEdit.setObjectName("textEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setPlaceholderText("Имя")
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 70, 251, 41))
        self.lineEdit_2.setObjectName("textEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setPlaceholderText("Отчество")
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 120, 251, 41))
        self.lineEdit_3.setObjectName("textEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setPlaceholderText("Гражданство")
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 270, 251, 41))
        self.lineEdit_4.setObjectName("textEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setPlaceholderText("Серия, номер паспорта")
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 220, 251, 41))
        self.lineEdit_5.setValidator(QIntValidator())
        self.lineEdit_5.setObjectName("textEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setPlaceholderText("Номер тел.")
        rx = QtCore.QRegularExpression("[0-9]{11}")
        val = QtGui.QRegularExpressionValidator(rx)
        self.lineEdit_6.setValidator(val)
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 320, 251, 41))
        self.lineEdit_6.setObjectName("textEdit_6")
        buy_tic.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(buy_tic)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menubar.setObjectName("menubar")
        buy_tic.setMenuBar(self.menubar)

        self.retranslateUi(buy_tic)
        self.box_gender.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(buy_tic)

    def retranslateUi(self, buy_tic):
        _translate = QtCore.QCoreApplication.translate
        buy_tic.setWindowTitle(_translate("buy_tic", "Покупка билета"))
        self.box_gender.setItemText(0, _translate("buy_tic", "МУЖ"))
        self.box_gender.setItemText(1, _translate("buy_tic", "ЖЕН"))
        self.but_buy.setText(_translate("buy_tic", "Купить билет"))
        self.but_buy_2.setText(_translate("buy_tic", "Вернуться в меню"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     buy_tic = QtWidgets.QMainWindow()
#     ui = Ui_buy_tic()
#     ui.setupUi(buy_tic)
#     buy_tic.show()
#     sys.exit(app.exec_())
