# Form implementation generated from reading ui file 'C:\Users\Stanislawski\Desktop\МРПС\Programm\interfaces\cashier.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CashierWindow(object):
    def setupUi(self, CashierWindow):
        CashierWindow.setObjectName("CashierWindow")
        CashierWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=CashierWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 60, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 290, 261, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        CashierWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CashierWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        CashierWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CashierWindow)
        self.statusbar.setObjectName("statusbar")
        CashierWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CashierWindow)
        QtCore.QMetaObject.connectSlotsByName(CashierWindow)

    def retranslateUi(self, CashierWindow):
        _translate = QtCore.QCoreApplication.translate
        CashierWindow.setWindowTitle(_translate("CashierWindow", "MainWindow"))
        self.label.setText(_translate("CashierWindow", "Кассир бля"))
        self.pushButton.setText(_translate("CashierWindow", "Назад"))



