# Form implementation generated from reading ui file 'C:\Users\Stanislawski\Desktop\МРПС\Programm\interfaces\cashier_main.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CashierMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1293, 516)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushbutton_cashier_buy_ticket = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushbutton_cashier_buy_ticket.setGeometry(QtCore.QRect(680, 420, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushbutton_cashier_buy_ticket.setFont(font)
        self.pushbutton_cashier_buy_ticket.setIconSize(QtCore.QSize(20, 20))
        self.pushbutton_cashier_buy_ticket.setObjectName("pushbutton_cashier_buy_ticket")
        self.pushbutton_return_cashier_ticket = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushbutton_return_cashier_ticket.setGeometry(QtCore.QRect(360, 420, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushbutton_return_cashier_ticket.setFont(font)
        self.pushbutton_return_cashier_ticket.setIconSize(QtCore.QSize(20, 20))
        self.pushbutton_return_cashier_ticket.setObjectName("pushbutton_return_cashier_ticket")
        self.pushbutton_to_sign = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushbutton_to_sign.setGeometry(QtCore.QRect(70, 420, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushbutton_to_sign.setFont(font)
        self.pushbutton_to_sign.setIconSize(QtCore.QSize(20, 20))
        self.pushbutton_to_sign.setObjectName("pushbutton_to_sign")
        self.pushbutton_revenue = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushbutton_revenue.setGeometry(QtCore.QRect(980, 420, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushbutton_revenue.setFont(font)
        self.pushbutton_revenue.setIconSize(QtCore.QSize(20, 20))
        self.pushbutton_revenue.setObjectName("pushbutton_revenue")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 1271, 361))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget::item { border-bottom: 1px solid black; }\n"
"QListWidget::item:selected { background-color: lightblue; color: black; }")
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(16, 0, 1261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1293, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Кассир главная"))
        self.pushbutton_cashier_buy_ticket.setText(_translate("MainWindow", "Купить билет"))
        self.pushbutton_return_cashier_ticket.setText(_translate("MainWindow", "Вернуть билет"))
        self.pushbutton_to_sign.setText(_translate("MainWindow", "Выйти из под-системы"))
        self.pushbutton_revenue.setText(_translate("MainWindow", "Подсчет дневной выручки"))
        self.label.setText(_translate("MainWindow", "Список рейсов"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
