# Form implementation generated from reading ui file 'C:\Users\Stanislawski\Desktop\МРПС\Programm\interfaces\client_main.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1316, 472)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_buy_ticket = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_buy_ticket.setGeometry(QtCore.QRect(570, 390, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_buy_ticket.setFont(font)
        self.btn_buy_ticket.setIconSize(QtCore.QSize(20, 20))
        self.btn_buy_ticket.setObjectName("btn_buy_tic")
        self.btn_return_ticket = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_return_ticket.setGeometry(QtCore.QRect(890, 390, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_return_ticket.setFont(font)
        self.btn_return_ticket.setIconSize(QtCore.QSize(20, 20))
        self.btn_return_ticket.setObjectName("btn_vozv_tic")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 1301, 341))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget::item { border-bottom: 1px solid black; }\n"
"QListWidget::item:selected { background-color: lightblue; color: black; }")
        self.listWidget.setObjectName("listWidget")
        self.btn_return = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_return.setGeometry(QtCore.QRect(250, 390, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_return.setFont(font)
        self.btn_return.setIconSize(QtCore.QSize(20, 20))
        self.btn_return.setObjectName("btn_buy_tic_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 0, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1316, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Клиент главная"))
        self.btn_buy_ticket.setText(_translate("mainWindow", "Купить билет"))
        self.btn_return_ticket.setText(_translate("mainWindow", "Вернуть билет"))
        self.btn_return.setText(_translate("mainWindow", "Выйти из под-системы"))
        self.label.setText(_translate("mainWindow", "Выберите рейс"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
