# Form implementation generated from reading ui file 'C:\Users\Stanislawski\Desktop\МРПС\Programm\interfaces\sign.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EnterWindow(object):
    def setupUi(self, EnterWindow):
        EnterWindow.setObjectName("EnterWindow")
        EnterWindow.setEnabled(True)
        EnterWindow.resize(1123, 742)
        self.Enter = QtWidgets.QWidget(parent=EnterWindow)
        self.Enter.setEnabled(True)
        self.Enter.setObjectName("Enter")
        self.label = QtWidgets.QLabel(parent=self.Enter)
        self.label.setGeometry(QtCore.QRect(0, 30, 1121, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.Enter)
        self.pushButton.setGeometry(QtCore.QRect(360, 560, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.Enter)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 560, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioButton = QtWidgets.QRadioButton(parent=self.Enter)
        self.radioButton.setGeometry(QtCore.QRect(520, 500, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.Enter)
        self.radioButton_2.setGeometry(QtCore.QRect(620, 500, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.Enter)
        self.radioButton_3.setGeometry(QtCore.QRect(410, 500, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_2 = QtWidgets.QLabel(parent=self.Enter)
        self.label_2.setGeometry(QtCore.QRect(300, 240, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.Enter)
        self.label_3.setGeometry(QtCore.QRect(300, 340, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(parent=self.Enter)
        self.textEdit.setGeometry(QtCore.QRect(290, 370, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.Enter)
        self.textEdit_2.setGeometry(QtCore.QRect(290, 260, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.Enter)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setGeometry(QtCore.QRect(450, 630, 431, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        EnterWindow.setCentralWidget(self.Enter)
        self.menubar = QtWidgets.QMenuBar(parent=EnterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        EnterWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=EnterWindow)
        self.statusbar.setObjectName("statusbar")
        EnterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EnterWindow)
        QtCore.QMetaObject.connectSlotsByName(EnterWindow)

    def retranslateUi(self, EnterWindow):
        _translate = QtCore.QCoreApplication.translate
        EnterWindow.setWindowTitle(_translate("EnterWindow", "Вход"))
        self.label.setText(_translate("EnterWindow", "AITech Airways"))
        self.pushButton.setText(_translate("EnterWindow", "Войти"))
        self.pushButton_2.setText(_translate("EnterWindow", "Зарегистрироваться"))
        self.radioButton.setText(_translate("EnterWindow", "Кассир"))
        self.radioButton_2.setText(_translate("EnterWindow", "Клиент"))
        self.radioButton_3.setText(_translate("EnterWindow", "Админ"))
        self.label_2.setText(_translate("EnterWindow", "Введите логин:"))
        self.label_3.setText(_translate("EnterWindow", "Введите пароль:"))
        self.textBrowser.setHtml(_translate("EnterWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))



