# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_User.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 516)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 39, 600, 321))
        self.listView.setObjectName("listView")
        self.btn_buy_tic = QtWidgets.QPushButton(self.centralwidget)
        self.btn_buy_tic.setGeometry(QtCore.QRect(370, 380, 200, 40))
        self.btn_buy_tic.setIconSize(QtCore.QSize(20, 20))
        self.btn_buy_tic.setObjectName("btn_buy_tic")
        self.btn_vozv_tic = QtWidgets.QPushButton(self.centralwidget)
        self.btn_vozv_tic.setGeometry(QtCore.QRect(70, 380, 200, 40))
        self.btn_vozv_tic.setIconSize(QtCore.QSize(20, 20))
        self.btn_vozv_tic.setObjectName("btn_vozv_tic")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 600, 40))
        self.label.setWordWrap(False)
        self.label.setIndent(6)
        self.label.setObjectName("label")
        self.btn_ident = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ident.setGeometry(QtCore.QRect(70, 420, 200, 40))
        self.btn_ident.setIconSize(QtCore.QSize(20, 20))
        self.btn_ident.setObjectName("btn_ident")
        self.btn_revenue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_revenue.setGeometry(QtCore.QRect(370, 420, 200, 40))
        self.btn_revenue.setIconSize(QtCore.QSize(20, 20))
        self.btn_revenue.setObjectName("btn_revenue")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_buy_tic.setText(_translate("MainWindow", "Купить билет"))
        self.btn_vozv_tic.setText(_translate("MainWindow", "Вернуть билет"))
        self.label.setText(_translate("MainWindow", "Список рейсов"))
        self.btn_ident.setText(_translate("MainWindow", "Идентификация"))
        self.btn_revenue.setText(_translate("MainWindow", "Подсчет дневной выручки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
