# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RevenueWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CashRevenue(object):
    def setupUi(self, CashRevenue):
        CashRevenue.setObjectName("CashRevenue")
        CashRevenue.resize(363, 200)
        self.centralwidget = QtWidgets.QWidget(CashRevenue)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.revenue_button = QtWidgets.QPushButton(self.centralwidget)
        self.revenue_button.setGeometry(QtCore.QRect(190, 110, 161, 31))
        self.revenue_button.setObjectName("revenue_button")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(10, 110, 161, 31))
        self.back_button.setObjectName("back_button")
        CashRevenue.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CashRevenue)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 363, 21))
        self.menubar.setObjectName("menubar")
        CashRevenue.setMenuBar(self.menubar)

        self.retranslateUi(CashRevenue)
        QtCore.QMetaObject.connectSlotsByName(CashRevenue)

    def retranslateUi(self, CashRevenue):
        _translate = QtCore.QCoreApplication.translate
        CashRevenue.setWindowTitle(_translate("CashRevenue", "CashRevenue"))
        self.label.setText(_translate("CashRevenue", "Подсчет дневной выручки"))
        self.revenue_button.setText(_translate("CashRevenue", "подсчитать выручку"))
        self.back_button.setText(_translate("CashRevenue", "вернуться в меню"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CashRevenue = QtWidgets.QMainWindow()
    ui = Ui_CashRevenue()
    ui.setupUi(CashRevenue)
    CashRevenue.show()
    sys.exit(app.exec())
